MODEL:
  MASK_ON: True
  KEYPOINT_ON: True
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
    FREEZE_AT: 4
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    DEPTH: 50
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  ANCHOR_GENERATOR:
    SIZES: [[32], [64], [128], [256], [512]]  # One size for each in feature map
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]  # Three aspect ratios (same for all in feature maps)
  RPN:
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
    PRE_NMS_TOPK_TRAIN: 2000  # Per FPN level
    PRE_NMS_TOPK_TEST: 1000  # Per FPN level
    POST_NMS_TOPK_TRAIN: 1500
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: "StandardROIHeads"
    IN_FEATURES: [ "p2", "p3", "p4", "p5" ]
    NUM_CLASSES: 2
    # NUM_CLASSES: 1  # one class only
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
  ROI_MASK_HEAD:
    NAME: "MaskRCNNConvUpsampleHead"
    NUM_CONV: 4
    POOLER_RESOLUTION: 14
  ROI_KEYPOINT_HEAD:
    NUM_KEYPOINTS: 8
    NAME: "KRCNNConvDeconvUpsampleHead"  # without 
    # NAME: "KRCNNConvDeconvUpsampleHeadOwn"  # with VP loss
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.001
  GAMMA: 0.25
  LR_SCHEDULER_NAME: WarmupCosineLR
  WARMUP_METHOD: linear
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 1000
  MAX_ITER: 10000
  CHECKPOINT_PERIOD: 500
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
TEST:
  EVAL_PERIOD: 500
VERSION: 2