_BASE_: "./Base-RCNN-FPN.yaml"
MODEL:
  BACKBONE:
    NAME: 'build_mnasnet_fpn_backbone'
  FPN:
    IN_FEATURES: ['p2', 'p3', 'p4', 'p5', 'p6']
DATASETS:
  TRAIN: ("parcel3d_train", )
  TEST: ("parcel3d_validation", "parcel3d_real_validation" )
OUTPUT_DIR: "./output/mnasnet/01"
