_BASE_: "./Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "https://dl.fbaipublicfiles.com/cubercnn/omni3d/cubercnn_Res34_FPN.pth"
  BACKBONE:
    NAME: 'build_resnet_from_vision_fpn_backbone'
  RESNETS:
    DEPTH: 34
    TORCHVISION: True
  FPN:
    IN_FEATURES: ['p2', 'p3', 'p4', 'p5', 'p6']
DATASETS:
  TRAIN: ("parcel3d_train", )
  TEST: ("parcel3d_validation", "parcel3d_real_validation" )
OUTPUT_DIR: "./output/resnet34/01"