_BASE_: "./Base-RCNN-FPN.yaml"
MODEL:
  DEVICE: "cpu"
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    DEPTH: 50
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
DATASETS:
  TRAIN: ("tampar_sample_validation", )
SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 0.01
  WARMUP_ITERS: 0
  MAX_ITER: 2
OUTPUT_DIR: "./output/test"